title: Apollo Documentation
description: Ascension Engineering, Inc.
author: Apollo Documentation
logo: /assets/asc_eng.svg
github: https://github.com/AscensionEngineering/
about: Ascension Engineering, Inc.
# disqus_shortname: aboutashu
# google_analytics: UA-72862926-1

permalink: :title

url: "https://ascensionengineering.github.io"
# url: "http://127.0.0.1:4000"
baseurl: "/"
fullurl: "https://ascensionengineering.github.io/"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
